repos:
-   repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
    -   id: black
-   repo: https://github.com/pycqa/flake8
    rev: '7.0.0'  # pick a git hash / tag to point to
    hooks:
    -   id: flake8
